from enum import Enum

class Character(object):
    def __init__(self, row):
        self.CharacterNameEnum = CharacterEnum(row[21])

        self.dashAndRunAccelerationA = row[0]
        self.bubbleRatio = row[1]
        self.friction = row[2]
        self.airMobilityB = row[3]
        self.runAcceleration = row[4]
        self.kirbyStarDamage = row[5]
        self.numberOfJumps = row[6]
        self.jumpHInitialVelocity = row[7]
        self.walkAcceleration = row[8]
        self.jab3Window = row[9]
        self.doubleJumpMomentum = row[10]
        self.initialWalkVelocity = row[11]
        self.jumpVInitialVelocity = row[12]
        self.gravity = row[13]
        self.walkMaximumVelocity = row[14]
        self.maxAerialHVelocity = row[15]
        self.iceTraction = row[16]
        self.walljumpVVelocity = row[17]
        self.runAnimationScaling = row[18]
        self.walljumpHVelocity = row[19]
        self.jumpStartup = row[20]
        self.characterName = row[21]
        self.rapidJabWindow = row[22]
        self.victoryScreenWindowModelScaling = row[23]
        self.dairLandingLag = row[24]
        self.weight = row[25]
        self.bairLandingLag = row[26]
        self.ledgejumpHorizontalVelocity = row[27]
        self.fairLandingLag = row[28]
        self.shorthopVInitialVelocity = row[29]
        self.cameraTargetZoomBone = row[30]
        self.airJumpMultiplier = row[31]
        self.normalLandingLag = row[32]
        self.specialJumpAction = row[33]
        self.itemThrowVelocity = row[34]
        self.ledgejumpVertical = row[35]
        self.dashAndRunAccelerationB = row[36]
        self.airMobilityA = row[37]
        self.midWalkPoint = row[38]
        self.airFriction = row[39]
        self.dashInitialVelocity = row[40]
        self.modelScaling = row[41]
        self.jumpHMaximumVelocity = row[42]
        self.nairLandingLag = row[43]
        self.question = row[44]
        self.groundAirJumpMomentumMultiplier = row[45]
        self.uairLandingLag = row[46]
        self.turnDuration = row[47]
        self.fastWalkMin = row[48]
        self.fastFallTerminalVelocity = row[49]
        self.shieldBreakInitialVelocity = row[50]
        self.shieldSize = row[51]
        self.jab2Window = row[52]
        self.walkAnimationSpeed = row[53]
        self.terminalVelocity = row[54]
        self.weightDepThrowSpeedFlags = row[55]
        self.dashAndRunTerminalVelocity = row[56]
        self.jumpAnimationFrames = row[57]

class CharacterEnum(Enum):
    Bowser = "Bowser"
    CaptainFalcon = "Captain Falcon"
    DonkeyKong = "Donkey Kong"
    DrMario = "Dr Mario"
    Falco = "Falco"
    Fox = "Fox"
    GameAndWatch = "Game & Watch"
    Ganondorf = "Ganondorf"
    IceClimbersNana = "Ice Climbers - Nana"
    IceClimbersPopo = "Ice Climbers - Popo"
    Jigglypuff = "Jigglypuff"
    Kirby = "Kirby"
    Link = "Link"
    Luigi = "Luigi"
    Mario = "Mario"
    Marth = "Marth"
    Mewtwo = "Mewtwo"
    Ness = "Ness"
    Peach = "Peach"
    Pichu = "Pichu"
    Pikachu = "Pikachu"
    Roy = "Roy"
    Samus = "Samus"
    Sheik = "Sheik"
    Yoshi = "Yoshi"
    YoungLink = "Young Link"
    Zelda = "Zelda"